clc;
clear;
close all;

%% ============================================================
%  典型工况目标函数检查入口
%  运行本脚本可完成：
%  设计水头典型工况仿真 -> 设置归一化参考值 -> 计算目标函数分项。
%  本脚本不调用优化算法。
%% ============================================================

p0 = psu_default_params();
p0 = set_operating_head(p0, p0.ref.Hr);
p0.plot.output_dir = fullfile(pwd, 'typical_condition_results', datestr(now, 'yyyymmdd_HHMMSS'));
if ~exist(p0.plot.output_dir, 'dir')
    mkdir(p0.plot.output_dir);
end

[p, out_typical, m_typical, x_typical] = prepare_objective_params(p0);
[J_typical, m_obj] = objective_startup(x_typical, p);

fprintf('\n========== 设计水头典型工况指标 ==========%s', newline);
print_metrics_cn(m_typical);

fprintf('\n========== 设计水头典型工况目标函数 ==========%s', newline);
fprintf('J_typical = %.6f\n', J_typical);
fprintf('J_raw     = %.6f\n', m_obj.objective_raw);
fprintf('penalty   = %.6f\n', m_obj.penalty);

fprintf('\n========== 目标函数分项，已按典型工况归一化 ==========%s', newline);
fprintf('启动时间项       = %.6f\n', m_obj.obj_terms.t_start);
fprintf('转速超调项       = %.6f\n', m_obj.obj_terms.overshoot);
fprintf('终值误差项       = %.6f\n', m_obj.obj_terms.final_error);
fprintf('稳定段 IAE 项    = %.6f\n', m_obj.obj_terms.speed_iae);
fprintf('蜗壳压力项       = %.6f\n', m_obj.obj_terms.hc_max);
fprintf('尾水波动项       = %.6f\n', m_obj.obj_terms.ht_range);
fprintf('导叶速率项       = %.6f\n', m_obj.obj_terms.guide_rate);

%% 保存检查表
metric_name = { ...
    'J_typical'; ...
    'J_raw'; ...
    'penalty'; ...
    't_start_s'; ...
    'n_max_rpm'; ...
    'overshoot_pu'; ...
    'speed_dev_pu'; ...
    'final_speed_error_pu'; ...
    'speed_iae_post_pid'; ...
    'speed_iae_all'; ...
    'hc_max_m'; ...
    'ht_range_m'; ...
    'ht_min_m'; ...
    'guide_rate_rms'};

metric_value = [ ...
    J_typical; ...
    m_obj.objective_raw; ...
    m_obj.penalty; ...
    m_typical.t_start_s; ...
    m_typical.n_max_rpm; ...
    m_typical.overshoot_base_pu; ...
    m_typical.speed_dev_pu; ...
    m_typical.final_speed_error_pu; ...
    m_typical.speed_iae; ...
    m_typical.speed_iae_all; ...
    m_typical.hc_max_m; ...
    m_typical.ht_range_m; ...
    m_typical.ht_min_m; ...
    m_typical.guide_rate_rms];

T_typical = table(metric_name, metric_value, 'VariableNames', {'name', 'value'});
safe_writetable_local(T_typical, p.plot.output_dir, 'table_typical_condition_check.csv');

plot_typical_condition_cn(out_typical, p, m_typical);

save(fullfile(p.plot.output_dir, 'workspace_typical_condition.mat'), ...
    'p', 'x_typical', 'out_typical', 'm_typical', 'J_typical', 'm_obj', 'T_typical');

fprintf('\n典型工况检查结果已保存到：%s%s', p.plot.output_dir, newline);

function safe_writetable_local(T, output_dir, filename)
file = fullfile(output_dir, filename);
try
    writetable(T, file);
catch ME
    [~, name, ext] = fileparts(filename);
    alt = [name '_' datestr(now, 'yyyymmdd_HHMMSS') ext];
    warning('写入 %s 失败：%s。已改写为 %s。', filename, ME.message, alt);
    writetable(T, fullfile(output_dir, alt));
end
end
